Zomato/Controllers/MenusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Zomato.DataLayer;
using Zomato.DataModels;
using System.Data.Entity;
using Zomato.ViewModels;
using System.ComponentModel.DataAnnotations;
using Zomato.Models;
using Microsoft.AspNet.Identity;
using Zomato.Global;

namespace Zomato.Controllers
{
    public class MenusController : Controller
    {
        // GET: Menus

        ApplicatioDbContext dbc = null;
        ApplicationDbContext abc = null;
        public MenusController()
        {
            dbc = new ApplicatioDbContext();
            abc = new ApplicationDbContext();
        }
       
       // public MenuItemsViewModel MenuItemsView { get; set; }


        public ActionResult Index()
        {

            if (User.Identity.IsAuthenticated)
            {
                Globalvariable.CartCount = 0;
                Globalvariable.CartCount = dbc.ShoppingCarts.Where(m => m.ApplicationUserId == User.Identity.Name).ToList().Count;
            }
            var Menitm = dbc.MenuItems.Include(m => m.Category).Include(m => m.SubCategory).ToList();
            var viewModel = new MenuItemsViewModel
            {
                MenuItem=Menitm
            };
            return View(viewModel);
        }
        public ActionResult IndexAt(int id)
        {

            var Menitm = dbc.MenuItems.Include(m => m.Category).Include(m => m.SubCategory).Where(m => m.CategoryId.Equals(id)).ToList();
            var viewModel = new MenuItemsViewModel
            {
                MenuItem = Menitm
            };
            return View(viewModel);
        }
        public ActionResult Create()
        {
            ViewBag.cat = dbc.Categories.ToList();
            ViewBag.subcat = dbc.SubCategories.ToList();
            return View();
        }

        [HttpPost]
        public ActionResult Create(MenuItem menu )
        {
            //if(!ModelState.IsValid)
            //{
            //    return RedirectToAction("Create");
            //}
            
            
                if (Request.Files.Count >= 1)
                {
                    var photo = Request.Files[0];
                    var imgByte = new byte[photo.ContentLength - 1];
                    photo.InputStream.Read(imgByte, 0, photo.ContentLength - 1);
                    var base64st = Convert.ToBase64String(imgByte, 0, imgByte.Length);
                    menu.Image = base64st;
                }
                dbc.MenuItems.Add(menu);
                dbc.SaveChanges();
                return RedirectToAction("AIndex");
            
        }

        [Authorize]
        public ActionResult Details(int id)
        {
            ViewBag.shop = dbc.ShoppingCarts;
            ViewBag.user = User.Identity.GetUserId();
            var menit = dbc.MenuItems.Include(m => m.Category).Include(m => m.SubCategory).Where(m => m.Id == id).SingleOrDefault();
            return View(menit);
        }
        public ActionResult Edit(int id)
        {
            //var cat = dbc.Categories.ToList();
            //var subc = dbc.SubCategories.ToList();
            //var emit = dbc.MenuItems.SingleOrDefault(m => m.Id == id);
            //var vmid = new MenuItemsViewModel
            //{
            //    MenuItem = emit,
            //    Categories=cat,
            //    SubCategories=subc
            //};
            ViewBag.cat = dbc.Categories.ToList();
            ViewBag.subcat = dbc.SubCategories.ToList();
            var eem = dbc.MenuItems.Where(m => m.Id == id).SingleOrDefault();
            return View(eem);
           // return View(vmid);
        }

        [HttpPost]
        public ActionResult Edit(MenuItem menu)
        {
            var exmen = dbc.MenuItems.Where(m => m.Id == menu.Id).FirstOrDefault();
            if (Request.Files.Count >= 1)
            {
                var photo = Request.Files[0];
                var imgByte = new byte[photo.ContentLength - 1];
                photo.InputStream.Read(imgByte, 0, photo.ContentLength - 1);
                var base64st = Convert.ToBase64String(imgByte, 0, imgByte.Length);
                menu.Image = base64st;
            }
            exmen.Name = menu.Name;
            exmen.Description = menu.Description;
            exmen.Spicyness = menu.Spicyness;
            exmen.Image = menu.Image;
            exmen.CategoryId = menu.CategoryId;
            exmen.SubCategoryId = menu.SubCategoryId;
            exmen.Price = menu.Price;
            dbc.SaveChanges();
            return RedirectToAction("AIndex");
        }

        public ActionResult Delete(int id)
        {
            ViewBag.cat = dbc.Categories.ToList();
            ViewBag.subcat = dbc.SubCategories.ToList();
            var eem = dbc.MenuItems.Where(m => m.Id == id).SingleOrDefault();
            return View(eem);
        }
        [HttpPost]
        public ActionResult Delete(int id,MenuItem menu)
        {
            var depmen = dbc.MenuItems.Where(m => m.Id==id).FirstOrDefault();
            dbc.MenuItems.Remove(depmen);
            dbc.SaveChanges();
            return RedirectToAction("AIndex");
        }

        [HttpPost]
        public ActionResult AddToCart(ShoppingCart cart)
        {
            bool Exis = false;

            if (User.Identity.IsAuthenticated)
            {
               
                var scart = dbc.ShoppingCarts.ToList();
                foreach (var item in scart)
                {
                    if ((cart.ApplicationUserId == item.ApplicationUserId) && (cart.MenuItemId == item.MenuItemId))
                    {
                        Exis = true;
                        item.Quantity=item.Quantity+1;
                    }
                }
                if(Exis==false)
                {
                    cart.Quantity = 1;
                    dbc.ShoppingCarts.Add(cart);
                }

                Globalvariable.CartCount = Globalvariable.CartCount + 1;
                dbc.SaveChanges();
                return RedirectToAction("Index");
            }
            else
            {
                return RedirectToAction("Index");
            }
        }
        [Authorize]
        public ActionResult UrCart()
        {
            ViewBag.uId = User.Identity.GetUserId();
            string auId = ViewBag.uId;
            var shoppingcart = dbc.ShoppingCarts.Where(e=>e.ApplicationUserId==auId).ToList();
            // var cartItems = GetCartItems(auId);
            var viewModel = new MenuItemsViewModel
            {
                ShoppingCarts = shoppingcart
            };
            return View(viewModel);
        }

        public ActionResult PlusItems(int cartId)
        {
            var cart = dbc.ShoppingCarts.FirstOrDefault(e => e.Id == cartId);
            cart.Quantity += 1;
            Globalvariable.CartCount = Globalvariable.CartCount + 1;
            dbc.SaveChanges();
            return RedirectToAction("UrCart");

        }
        public ActionResult MinusItems(int cartId)
        {
            var cart = dbc.ShoppingCarts.FirstOrDefault(e => e.Id == cartId);

            if (cart.Quantity == 0)
            {
                dbc.ShoppingCarts.Remove(cart);
               
                dbc.SaveChanges();
            }
            else
            {
                cart.Quantity -= 1;
                Globalvariable.CartCount = Globalvariable.CartCount - 1;
                dbc.SaveChanges();
            }
            return RedirectToAction("UrCart");

        }
        public ActionResult Remove(int cartId)
        {
            var cart = dbc.ShoppingCarts.FirstOrDefault(e => e.Id == cartId);
            dbc.ShoppingCarts.Remove(cart);
            Globalvariable.CartCount = Globalvariable.CartCount - 1;
            dbc.SaveChanges();
            return RedirectToAction("UrCart");
        }

        public ActionResult OderSumary()
        {
            ViewBag.uId = User.Identity.GetUserId();
            string auId = ViewBag.uId;
            var shoppingcart = dbc.ShoppingCarts.Where(e=>e.ApplicationUserId==auId).ToList();
            // var cartItems = GetCartItems(auId);
            var viewModel = new MenuItemsViewModel
            {
                ShoppingCarts = shoppingcart
            };
            return View(viewModel);
        }

        public ActionResult CRemove(string UName)
        {
            var cart = dbc.ShoppingCarts.Where(e => e.ApplicationUserId == UName);
            dbc.ShoppingCarts.RemoveRange(cart);
            dbc.SaveChanges();
            return RedirectToAction("OrderHistory");
        }

        public ActionResult OrderHistory()
        {


            return View();
        }
        public ActionResult AIndex()
        {

            var Menitm = dbc.MenuItems.Include(m => m.Category).Include(m => m.SubCategory).ToList();
            var viewModel = new MenuItemsViewModel
            {
                MenuItem = Menitm
            };
            return View(viewModel);
        }
    }

}

Zomato/Views/Menus/AIndex.cshtml
@model Zomato.ViewModels.MenuItemsViewModel
@{
    ViewBag.Title = "AIndex";
}

<h2>ADmin Mode</h2>


<a href="/Menus/create" class="btn btn-info">Add new food Item</a>
<br/>
<br/>
<div class="container">
    <table class="table">
        @foreach (var i in Model.MenuItem)
        {
            <tr class="table-condensed">
                <td><img src="data:img;base64,@i.Image" width="150" /></td>
                <td >
                    <strong> @Html.DisplayFor(m => i.Name)</strong>
                    <br />
                    <br />
                    Category:@Html.DisplayFor(m => i.Category.CName)
                </td>
                <td >
                    <i style="color: yellow;" class="fas fa-pepper-hot"></i>
                    @Html.DisplayFor(m => i.Spicyness)
                </td>
                <td>
                    &#8377; @Html.DisplayFor(m => i.Price)
                </td>

                <td>


                    @Html.ActionLink("Show Details", "Details", "Menus", new { id = i.Id }, new { @class = "btn btn-info" })
                </td>

                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = i.Id }, "Menus")
                </td>
                <td>
                    @Html.ActionLink("Delete", "Delete", new { id = i.Id }, "Menus")
                </td>
            </tr>
        }
    </table>
</div>

Zomato/Views/Menus/Create.cshtml
@model Zomato.DataModels.MenuItem
@{
    ViewBag.Title = "Create";
}

<h2>Add new Food Item</h2>

<form action="/menus/create" method="post" enctype="multipart/form-data">

    <div class="form">
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.Name)
            @Html.HiddenFor(m => m.Id)
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.Description)
            @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.Spicyness)
            @Html.EnumDropDownListFor(m => m.Spicyness, new { htmlAttributes = new { @class = "form-control" } })

        </div>
        <div class="form-group">
            <label for="Image">Image</label>
            <input type="file" class="form-control-file" name="Image" />

        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.CategoryId)
            @*@Html.DropDownListFor(m => m.MenuItem.CategoryId, new SelectList(Model.Categories, "CId", "CName"), "Select the Category", new { @class = "form-control" })*@
            <select class="form-control" id="CategoryId" name="CategoryId">
                <option value="">please select dept</option>
                @foreach (var s in ViewBag.cat)
                {
                    <option value="@s.CId">@s.CName</option>
                }
            </select>

        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.SubCategoryId)
            @*@Html.DropDownListFor(m => m.SubCategoryId, new SelectList(Model., "Id", "Name"), "Select the Category", new { @class = "form-control" })*@

            <select class="form-control" id="SubCategoryId" name="SubCategoryId">
                <option value="">please select dept</option>
                @foreach (var s in ViewBag.subcat)
                {
                    <option value="@s.Id">@s.Name</option>
                }
            </select>

        </div>
        <div class="form-group col-md-6">

            @Html.LabelFor(m => m.Price)
            @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        </div>
    </div>
    @Html.ValidationSummary()
    <button type="submit" class="btn btn-success">Add Item</button>
    <a class="btn btn-dark" href="/Menus/aindex">Cancel</a>
    </form>

Zomato/Views/Menus/Delete.cshtml
@model Zomato.DataModels.MenuItem
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<form action="/menus/delete/@Model.Id" method="post">
    <div class="form">
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.Name)

            @Html.HiddenFor(m => m.Id)
            @Model.Name
        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.Category.CName)
            @Model.Category.CName
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.Price)
            @Model.Price

        </div>
        

    </div>
        </div>
    <button type="submit" class="btn btn-danger">Delete </button>
    <a class="btn btn-dark" href="/menus/aindex">Cancel</a>
</form>

Zomato/Views/Menus/Details.cshtml
@model Zomato.DataModels.MenuItem
@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>
<h2>Details of Food Item</h2>

<br />
<head>
    <style>
       /* tr {
            height: 45px;
            
            color:aliceblue;
            font-style:italic;

        }*/

        body.background {
            background-image: url('../../Images/PicsArt_02-25-02.59.15.jpg');
           
            border: 2px solid black;
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center;
            background-size: 100%,100%;
            *
            opacity: 1;
        }
        div.transbox {
            margin: 30px;
            background-color: #ffffff;
            border: 1px solid black;
            opacity: 0.8;
        }
            table.transboxa  {
                margin: 5%;
                font-weight: bold;
                color: #000000;
                font-family:'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;
                font-size:20px;
                
                
                
            }
        img {
            display: block;
            object-fit: cover;
        }
        /*.body {
             background-image: url('../../Images/PicsArt_02-25-02.59.15.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-position: center;
            background-size: 100%,100%;*/
            /*background-color: antiquewhite;*/
        /*}*/
    </style>
    
</head>
<br />
<h2>@Model.Name Details</h2>
<br />
<body class="background">
    


        @using (Html.BeginForm("AddToCart", "Menus", new { ApplicationUserId = ViewBag.user, MenuItemId = Model.Id }))
        {
            <div class="transbox">
            <table class="container-fluid transboxa">
                <tr class="row-height">
                    <th width="20%">Item ID : </th>
                    <td><strong>@Model.Id</strong></td>
                </tr>
                <tr>
                    <th>Item Price : </th>
                    <td><strong>@Model.Price</strong></td>
                </tr>
                <tr>
                    <th>Item Spice : </th>
                    <td><strong>@Model.Spicyness</strong></td>
                </tr>
                <tr>
                    <th>Item Type : </th>
                    <td><strong>@Model.Category.CName</strong></td>
                </tr>
                <tr>
                    <th>Item Category : </th>
                    <td><strong>@Model.SubCategory.Name</strong></td>
                </tr>
                <tr>
                    <th>Item Description : </th>
                    <td style="flex-wrap:wrap"><strong>@Model.Description</strong></td>
                </tr>
                <tr>
                    <th>Item Presentation : </th>
                    <td>
                        <img src="data:img;base64,@Model.Image" alt="Chicken Biryani" width="200" height="200">
                    </td>
                </tr>
            </table>
                </div>

            <div class="col-md-4">
                <button type="submit" value="AddToCart" class="btn btn-primary form-control">Add to Cart</button>
            </div>

            <a href="/Menus/Index" class="btn btn-info">Back</a>
        }
        
    
   

</body>















@*<div >
    <div class="col-md-offset-6" style="float:right;">
        <img src="data:img;base64,@Model.Image"  width="150" height="150" style="border-radius:5px;border: solid #bbb9b9;" />
    </div>
    <div  style="float:left">
        <div class="col-8">
            <fieldset disabled>
                <div class="form-group row">
                    <div class="col-4">
                        <label class="text-info font-weight-bold">Dish Name:</label>
                    </div>
                    <div class="col-8">
                        @Html.DisplayFor(m => m.Name)
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label class="text-info font-weight-bold">Discription:</label>
                    </div>
                    <div class="col-8 row">
                        @Html.DisplayTextFor(m => m.Description)
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label class="text-info font-weight-bold">Discription:</label>
                    </div>
                    <div class="col-8 row">
                        @Html.DisplayFor(m => m.Price)
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label class="text-info font-weight-bold">Category:</label>
                    </div>
                    <div class="col-8 row">
                        @Html.DisplayFor(m => m.Category.CName)
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label class="text-info font-weight-bold">SubCategory:</label>
                    </div>
                    <div class="col-8 row">
                        @Html.DisplayFor(m => m.SubCategory.Name)
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-4">
                        <label class="text-info font-weight-bold">Spicyness:</label>
                    </div>
                    <div class="col-8 row">
                        @Html.DisplayFor(m => m.Spicyness)
                    </div>
                </div>
            </fieldset>
            </div>

    </div>
      </div>*@


@*<table class="table">
        <tr>
            <th>Dish Name</th>
        </tr>
    </table>*@

Zomato/Views/Menus/Edit.cshtml
@model Zomato.DataModels.MenuItem
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<form action="/Menus/Edit" method="post" enctype="multipart/form-data">
    <div class="form">
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.Name)
            @Html.HiddenFor(m => m.Id)
            @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Name, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.Description)
            @Html.TextBoxFor(m => m.Description, new { @class = "form-control" })
            @Html.ValidationMessageFor(m => m.Description, "", new { @class = "text-danger" })
        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.Spicyness)
            @Html.EnumDropDownListFor(m => m.Spicyness, new { htmlAttributes = new { @class = "form-control" } })

        </div>
        <div class="form-group">
            <label for="Image">Image</label>
            <input type="file" class="form-control-file" name="Image" />

        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.CategoryId)
            @*@Html.DropDownListFor(m => m.CategoryId, new SelectList(Model.Categories, "CId", "CName"), "select dept name", new { @class = "form-control" })*@
            <select class="form-control" id="CategoryId" name="CategoryId">
                <option value="">please select dept</option>
                @foreach (var s in ViewBag.cat)
                {
                    <option value="@s.CId">@s.CName</option>
                }
            </select>

        </div>
        <div class="form-group col-md-6">
            @Html.LabelFor(m => m.SubCategoryId)
            @*@Html.DropDownListFor(m => m.MenuItem.SubCategoryId, new SelectList(Model.SubCategories, "Id", "Name"), "select dept name", new { @class = "form-control" })*@
            <select class="form-control" id="SubCategoryId" name="SubCategoryId">
                <option value="">please select dept</option>
                @foreach (var s in ViewBag.subcat)
                {
                    <option value="@s.Id">@s.Name</option>
                }
            </select>

        </div>
        <div class="form-group col-md-6">

            @Html.LabelFor(m => m.Price)
            @Html.TextBoxFor(m => m.Price, new { @class = "form-control" })
        </div>
    </div>
    <button type="submit" class="btn btn-success">Make Changes</button>
    <a class="btn btn-dark" href="/Menus/AIndex">Cancel</a>
</form>

Zomato/Views/Menus/Index.cshtml
@model Zomato.ViewModels.MenuItemsViewModel
@{
    ViewBag.Title = "Index";
}
<head>
    <style>
        tr {
            height: 45px;
        }

        .table td, .table th {
            font-size: 20px;
            font-family: Calibri;
            font-display: block;
        }

        body {
            background-image: url('../../Images/menuall2.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
        }
    </style>
    <link href="~/Content/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/fontawesome-all.css" rel="stylesheet" />
</head>
<body>
    <center>
    <a href="/menus/Index" class="btn btn-primary">Show All</a>
    <a href="/menus/IndexAt/1" class="btn btn-primary">Apetizers</a>
    <a href="/menus/IndexAt/2" class="btn btn-primary">Main Course</a>
    <a href="/menus/IndexAt/3" class="btn btn-primary">Dessert</a>
    <a href="/menus/IndexAt/4" class="btn btn-primary">Beverages</a>
        </center>
    @*<h2>Main Menu</h2>
        <a href="/Menus/create" class="btn btn-info">Add new food Item</a>*@
    <br />
    <br />

    @*<table class="table table-striped border">
        <tr class="table-secondary">
            <th>
                @Html.DisplayNameFor(m => m.Image)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Name)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Category.CName)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.SubCategory.Name)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Price)
            </th>
            <th></th>
            <th></th>
            <th></th>

        </tr>*@
    <div class="container">
        <table class="table">
            @foreach (var i in Model.MenuItem)
            {
            <tr class="table-condensed">
                <td><img src="data:img;base64,@i.Image" width="150" /></td>
                <td style="color:antiquewhite">
                    <strong> @Html.DisplayFor(m => i.Name)</strong>
                    @if ((int)i.Spicyness == 3)
                    {

                        <i style="color:red;" class="fas fa-pepper-hot tooltipDesign" alt="@i.Spicyness" title="@i.Spicyness"></i>


                    }
                    @if ((int)i.Spicyness == 2)
                    {

                        <i style="color:orangered;" class="fas fa-pepper-hot tooltipDesign" alt="@i.Spicyness" title="@i.Spicyness"></i>

                    }
                    @if ((int)i.Spicyness == 1)
                    {

                        <i style="color:forestgreen;" class="fas fa-pepper-hot tooltipDesign" alt="@i.Spicyness" title="@i.Spicyness"></i>

                    }
                    <br />
                    <br />
                    Category:@Html.DisplayFor(m => i.Category.CName)

                </td>
                <td style="color:white">
                    
                    @*<i style="color:red;" class="fas fa-pepper-hot tooltipDesign" alt="@i.Spicyness" title="@i.Spicyness"></i>*@
                   
                </td>
                    <td style="color:white">
                        &#8377; @Html.DisplayFor(m => i.Price)
                    </td>

                    <td>


                        @Html.ActionLink("Show Details", "Details", "Menus", new { id = i.Id }, new { @class = "btn btn-info" })
                    </td>

                    @*<td>
                @Html.ActionLink("Edit", "Edit", new { id = i.Id }, "Menus")
            </td>*@
                    @*<td>
                @Html.ActionLink("Delete", "Delete", new { id = i.Id }, "Menus")
            </td>*@
                </tr>
            }
        </table>
    </div>
</body>
<script>
    var toolimg = document.getElementsByClassName("tooltipDesign");
    for (var i = 0; i < toolimg.length; i++) {
        toolimg[i].title = toolimg[i].title;
    }
</script>
@*else
    {
        <p>No Menu Items to show</p>
    }*@

Zomato/Views/Menus/IndexAt.cshtml
@model Zomato.ViewModels.MenuItemsViewModel
@{
    ViewBag.Title = "Index";
}
<head>
    <style>
        tr {
            height: 45px;
        }

        .table td, .table th {
            font-size: 20px;
            font-family: Calibri;
            font-display: block;
        }

        body {
            background-image: url('../../Images/menuall2.jpg');
            background-repeat: no-repeat;
            background-attachment: fixed;
            background-size: 100% 100%;
        }
    </style>
</head>
<body>
    <center>
        <a href="/menus/Index" class="btn btn-primary">Show All</a>
        <a href="/menus/IndexAt/1" class="btn btn-primary">Apetizers</a>
        <a href="/menus/IndexAt/2" class="btn btn-primary">Main Course</a>
        <a href="/menus/IndexAt/3" class="btn btn-primary">Dessert</a>
        <a href="/menus/IndexAt/4" class="btn btn-primary">Beverages</a>
    </center>
    @*<h2>Main Menu</h2>
        <a href="/Menus/create" class="btn btn-info">Add new food Item</a>*@
    <br />
    <br />

    @*<table class="table table-striped border">
        <tr class="table-secondary">
            <th>
                @Html.DisplayNameFor(m => m.Image)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Name)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Category.CName)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.SubCategory.Name)
            </th>
            <th>
                @Html.DisplayNameFor(m => m.Price)
            </th>
            <th></th>
            <th></th>
            <th></th>

        </tr>*@
    <div class="container">
        
        <table class="table">
            @foreach (var i in Model.MenuItem)
            {
                <tr class="table-condensed">
                    <td><img src="data:img;base64,@i.Image" width="150" /></td>
                    <td style="color:white">
                        @Html.DisplayFor(m => i.Name)
                        @if ((int)i.Spicyness == 3)
                        {

                            <i style="color:red;" class="fas fa-pepper-hot tooltipDesign" alt="@i.Spicyness" title="@i.Spicyness"></i>


                        }
                        @if ((int)i.Spicyness == 2)
                        {

                            <i style="color:orangered;" class="fas fa-pepper-hot tooltipDesign" alt="@i.Spicyness" title="@i.Spicyness"></i>

                        }
                        @if ((int)i.Spicyness == 1)
                        {

                            <i style="color:forestgreen;" class="fas fa-pepper-hot tooltipDesign" alt="@i.Spicyness" title="@i.Spicyness"></i>

                        }
                        <br />
                        <br />
                        Category:@Html.DisplayFor(m => i.Category.CName)

                    </td>
                    <td style="color:white">
                       
                    </td>
                    <td style="color:white">
                        @Html.DisplayFor(m => i.Price)
                    </td>
                    <td>
                        @Html.ActionLink("Show Details", "Details", "Menus", new { id = i.Id }, new { @class = "btn btn-info" })
                    </td>
                    @*<td>
                            @Html.ActionLink("Edit", "Edit", new { id = i.Id }, "Menus")
                        </td>*@
                    @*<td>
                            @Html.ActionLink("Delete", "Delete", new { id = i.Id }, "Menus")
                        </td>*@
                </tr>
            }
        </table>
    </div>
</body>
<script>
    var toolimg = document.getElementsByClassName("tooltipDesign");
    for (var i = 0; i < toolimg.length; i++) {
        toolimg[i].title = toolimg[i].title;
    }
</script>

@*else
    {
        <p>No Menu Items to show</p>
    }*@

Zomato/Views/Menus/OrderHistory.cshtml
@{
    ViewBag.Title = "OrderHistory";
}

<h2>Order Status::</h2>
<div class="container">
    <img src="~/Images/782-check-mark-success.gif" style="width:500px" />

    <h4>Order Recived.</h4>
   <h3>continue Shoping... <a href="/Menus/Index" class="btn btn-info">Back TO Menu</a></h3>
</div>